return {}
-- local vars = require("config.vars")
-- local funcs = require("config.functions")
--
-- local clfPath = function()
--   if vars.getOSLowerCase():match("windows") then
--     return os.getenv("UserProfile") .. "/.clang-format" -- Must create this folder
--   else -- I don't own/use a Mac, will update when/if I do
--     return os.getenv("HOME") .. "/.clang-format" -- Must create this folder
--   end
-- end
--
-- return {
--   {
--     "nvimtools/none-ls.nvim",
--     dependencies = {
--       "nvimtools/none-ls-extras.nvim",
--     },
--     event = "VeryLazy",
--     config = function()
--       local maxSize = 1.5 * 1024 * 1024 -- 1.5MB
--       local size = vim.fn.getfsize(vim.fn.expand("%"))
--       if size >= maxSize then
--         local clients = vim.lsp.get_clients()
--         for _, lclient in ipairs(clients) do
--           vim.lsp.stop_client(lclient)
--         end
--         return
--       end
--
--       local augroup = vim.api.nvim_create_augroup("LspFormatting", {})
--       local null_ls = require("null-ls")
--       local null_ls_utils = require("null-ls.utils")
--
--       local on_attach = function(client, bufnr)
--         if client.supports_method("textDocument/formatting") then
--           vim.api.nvim_clear_autocmds({ group = augroup, buffer = bufnr })
--           vim.api.nvim_create_autocmd("BufWritePre", {
--             group = augroup,
--             buffer = bufnr,
--             callback = function()
--               funcs.format(bufnr, false, 5000)
--             end,
--           })
--         end
--       end
--
--       local formatting = null_ls.builtins.formatting -- to setup formatters
--       -- local diagnostics = null_ls.builtins.diagnostics -- to setup linters
--       -- local actions = null_ls.builtins.code_actions -- to setup linters
--
--       local sources = {
--         formatting.clang_format.with({
--           disabled_filetypes = { "cs", "csharp" }, -- Don't want it messing with C#
--           extra_args = {
--             "-style=file:" .. vim.fn.expand(clfPath()),
--           },
--         }),
--
--         -- formatting.biome,
--         formatting.clang_format,
--         formatting.cmake_format,
--         formatting.csharpier,
--         formatting.gdformat,
--         -- formatting.prettier,
--         formatting.prettierd,
--         -- formatting.rustfmt,
--         formatting.shellharden,
--         -- formatting.sqlfluff,
--         formatting.stylua,
--
--         -- actions.gitsigns,
--         -- actions.gitsigns.with({
--         -- 	Callback to filter out unwanted actions
--         -- 	config = {
--         -- 	    filter_actions = function(title)
-- 	        return title:lower():match("blame") == nil -- filter out blame actions
--         -- 	    end,
--         -- 	},
--         -- }),
--         -- actions.refactoring,
--       }
--
--       local rootdir = function(fname)
--         return null_ls_utils.root_pattern(
--           ".null-ls-root",
--           "Makefile",
--           "CMakefile",
--           ".git",
--           ".sln",
--           "package.json",
--           "project.godot",
--           "configure.ac",
--           "configure.in",
--           "config.h.in",
--           "meson.build",
--           "meson_options.txt",
--           "build.ninja"
--         )(fname) or null_ls_utils.root_pattern("compile_commands.json", "compile_flags.txt")(
--           fname
--         ) or require("lspconfig.util").find_git_ancestor(fname)
--       end
--
--       null_ls.setup({
--         sources = sources,
--         root_dir = rootdir,
--         on_attach = function(client, bufnr)
--           on_attach(client, bufnr)
--         end,
--       })
--     end,
--   },
-- }
