return {}

-- return {
--   -- "ms-jpq/chadtree",
--   -- "nvim-tree/nvim-tree.lua",
--   "nvim-neo-tree/neo-tree.nvim",
--   version = false,
--   lazy = false,
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--     -- "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
--     "echasnovski/mini.nvim",
--     "MunifTanjim/nui.nvim",
--     { "3rd/image.nvim", opts = {} }, -- Optional image support in preview window: See `# Preview Mode` for more information
--   },
--   opts = function()
--     require("config.keymaps.filemanager")
--     return {
--       popup_border_style = "rounded", -- "double", "none", "rounded", "shadow", "single" or "solid"
--       event_handlers = {
--         {
--           event = "file_opened",
--           handler = function(file_path)
--             --auto close
--             require("neo-tree.command").execute({ action = "close" })
--             --clear search after opening a file
--             require("neo-tree.sources.filesystem").reset_search()
--           end,
--         },
--         {
--           event = "file_renamed",
--           handler = function(args)
--             -- fix references to file
--             print(args.source, " renamed to ", args.destination)
--           end,
--         },
--         {
--           event = "file_moved",
--           handler = function(args)
--             -- fix references to file
--             print(args.source, " moved to ", args.destination)
--           end,
--         },
--         {
--           event = "neo_tree_buffer_enter",
--           handler = function()
--             vim.cmd("highlight! Cursor blend=100")
--           end,
--         },
--         {
--           event = "neo_tree_buffer_leave",
--           handler = function()
--             vim.cmd("highlight! Cursor guibg=#5f87af blend=0")
--           end,
--         },
--         {
--           -- event = "neo_tree_window_before_open",
--           event = "neo_tree_window_after_open",
--           -- event = "neo_tree_buffer_enter",
--           handler = function(args)
--             -- require("neo-tree.command").execute({ action = "preview" })
--             -- require("neo-tree.command").execute({ action = "toggle_preview" })
--             -- require("neo-tree.command").execute({ action = "toggle-preview" })
--             -- require("neo-tree.sources.common.preview").toggle()
--             vim.opt_loca.relativenumber = true
--           end,
--         },
--       },
--       default_component_configs = {
--         diagnostics = {
--           symbols = {
--             hint = "⚑",
--             info = "»",
--             warn = "▲",
--             error = "✘",
--           },
--           highlights = {
--             hint = "DiagnosticSignHint",
--             info = "DiagnosticSignInfo",
--             warn = "DiagnosticSignWarn",
--             error = "DiagnosticSignError",
--           },
--         },
--         indent = {
--           indent_size = 2,
--           padding = 1,
--           -- indent guides
--           with_markers = true,
--           indent_marker = "├─",
--           last_indent_marker = "╰>",
--           highlight = "NeoTreeIndentMarker",
--           -- expander config, needed for nesting files
--           with_expanders = true, -- if nil and file nesting is enabled, will enable expanders
--           expander_collapsed = "├─",
--           expander_expanded = "╰>",
--           expander_highlight = "NeoTreeExpander",
--         },
--         icon = {
--           folder_closed = "",
--           folder_open = "",
--           folder_empty = "󰉖",
--           folder_empty_open = "󰷏",
--           -- The next two settings are only a fallback, if you use nvim-web-devicons and configure default icons there
--           -- then these will never be used.
--           default = "*",
--           highlight = "NeoTreeFileIcon",
--           provider = function(icon, node, state) -- default icon provider utilizes nvim-web-devicons if available
--             if node.type == "file" or node.type == "terminal" then
--               local success, web_devicons = pcall(require, "nvim-web-devicons")
--               local name = node.type == "terminal" and "terminal" or node.name
--               if success then
--                 local devicon, hl = web_devicons.get_icon(name)
--                 icon.text = devicon or icon.text
--                 icon.highlight = hl or icon.highlight
--               end
--             end
--           end,
--         },
--         git_status = {
--           symbols = {
--             -- Change type
--             added = "✚", -- NOTE: you can set any of these to an empty string to not show them
--             deleted = "✖",
--             modified = "",
--             renamed = "󰁕",
--             -- Status type
--             untracked = "?",
--             ignored = "",
--             unstaged = "○",
--             staged = "●",
--             conflict = "",
--           },
--           align = "right",
--         },
--       },
--       filesystem = {
--         window = {
--           mappings = {
--             ["P"] = {
--               "toggle_preview",
--               config = {
--                 use_float = false,
--                 use_image_nvim = true,
--                 -- title = "Neo-tree Preview", -- You can define a custom title for the preview floating window.
--               },
--             },
--           },
--         },
--         filtered_items = {
--           visible = true,
--           hide_dotfiles = false,
--           hide_gitignored = false,
--           hide_hidden = false, -- only works on Windows for hidden files/directories
--         },
--         use_libuv_file_watcher = true, -- Use the OS level file watchers to detect changes instead of nvim autocmd events.
--       },
--     }
--   end,
--   config = function(_, opts)
--     -- require("nvim-tree").setup(opts)
--     require("neo-tree").setup(opts)
--   end,
-- }
