return {}
-- return {
--   "nvim-neorg/neorg",
--   version = "*",
--   event = "VeryLazy",
--   ft = { "norg", "neorg" },
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--     "benlubas/neorg-interim-ls",
--   },
--   ["external.interim-ls"] = {
--     config = {
--       -- default config shown
--       completion_provider = {
--         -- Enable or disable the completion provider
--         enable = true,
--
--         -- Show file contents as documentation when you complete a file name
--         documentation = true,
--
--         -- Try to complete categories provided by Neorg Query. Requires `benlubas/neorg-query`
--         categories = false,
--
--         -- suggest heading completions from the given file for `{@x|}` where `|` is your cursor
--         -- and `x` is an alphanumeric character. `{@name}` expands to `[name]{:$/people:# name}`
--         people = {
--           enable = false,
--
--           -- path to the file you're like to use with the `{@x` syntax, relative to the
--           -- workspace root, without the `.norg` at the end.
--           -- ie. `folder/people` results in searching `$/folder/people.norg` for headings.
--           -- Note that this will change with your workspace, so it fails silently if the file
--           -- doesn't exist
--           path = "people",
--         },
--       },
--     },
--   },
--   config = function()
--     local neorg = require("neorg")
--
--     neorg.setup({
--       load = {
--         ["core.defaults"] = {}, -- Loads default behaviour
--         ["core.concealer"] = {}, -- Adds pretty icons to your documents
--         ["core.summary"] = {},
--         ["core.export.markdown"] = {
--           config = {
--             extension = "md",
--           },
--         },
--         ["core.completion"] = {
--           config = {
--             engine = {
--               module_name = "external.lsp-completion",
--             },
--           },
--         },
--         ["core.dirman"] = { -- Manages Neorg workspaces
--           config = {
--             workspaces = {
--               main = "~/norg",
--               learn = "~/norg/learn",
--               nwn = "~/nwstorage/norg",
--             },
--             default_workspace = "main",
--           },
--         },
--         ["core.export"] = {},
--       },
--     })
--   end,
--   build = ":Neorg sync-parsers",
-- }
