return {}
-- return {
--   {
--    "danilshvalov/org-modern.nvim",
--     event = "VeryLazy",
--     version = "*",
--     ft = { "org" },
--   },
--   {
--     "MeanderingProgrammer/render-markdown.nvim",
--     event = "VeryLazy",
--     version = "*",
--     ft = { "org" },
--     -- dependencies = { "nvim-treesitter/nvim-treesitter", "echasnovski/mini.nvim" }, -- if you use the mini.nvim suite
--     -- dependencies = { 'nvim-treesitter/nvim-treesitter', 'echasnovski/mini.icons' }, -- if you use standalone mini plugins
--     dependencies = { "nvim-treesitter/nvim-treesitter", "nvim-tree/nvim-web-devicons" }, -- if you prefer nvim-web-devicons
--     ---@module 'render-markdown'
--     ---@type render.md.UserConfig
--     opts = {},
--   },
--   {
--     "nvim-orgmode/org-bullets.nvim",
--     event = "VeryLazy",
--     version = "*",
--     ft = { "org" },
--   },
--   {
--     "nvim-orgmode/telescope-orgmode.nvim",
--     event = "VeryLazy",
--     version = "*",
--     ft = { "org" },
--     dependencies = {
--       "nvim-orgmode/orgmode",
--       "nvim-telescope/telescope.nvim",
--     },
--     config = function()
--       require("telescope").load_extension("orgmode")
--
--       vim.keymap.set("n", "<leader>r", require("telescope").extensions.orgmode.refile_heading)
--       vim.keymap.set("n", "<leader>fh", require("telescope").extensions.orgmode.search_headings)
--       vim.keymap.set("n", "<leader>li", require("telescope").extensions.orgmode.insert_link)
--
--       vim.api.nvim_create_autocmd("FileType", {
--         pattern = "org",
--         group = vim.api.nvim_create_augroup("orgmode_telescope_nvim", { clear = true }),
--         callback = function()
--           vim.keymap.set("n", "<leader>or", require("telescope").extensions.orgmode.refile_heading)
--         end,
--       })
--     end,
--   },
--   {
--     "michaelb/sniprun",
--     branch = "master",
--     version = "*",
--     ft = { "org" },
--     event = "VeryLazy",
--     build = "sh install.sh",
--     -- do 'sh install.sh 1' if you want to force compile locally
--     -- (instead of fetching a binary from the github release). Requires Rust >= 1.65
--
--     config = function()
--       require("sniprun").setup({
--         selected_interpreters = {}, --# use those instead of the default for the current filetype
--         repl_enable = {}, --# enable REPL-like behavior for the given interpreters
--         repl_disable = {}, --# disable REPL-like behavior for the given interpreters
--
--         interpreter_options = { --# interpreter-specific options, see doc / :SnipInfo <name>
--
--           --# use the interpreter name as key
--           GFM_original = {
--             use_on_filetypes = { "markdown.pandoc" }, --# the 'use_on_filetypes' configuration key is
--             --# available for every interpreter
--           },
--           Python3_original = {
--             error_truncate = "auto", --# Truncate runtime errors 'long', 'short' or 'auto'
--             --# the hint is available for every interpreter
--             --# but may not be always respected
--           },
--         },
--
--         --# you can combo different display modes as desired and with the 'Ok' or 'Err' suffix
--         --# to filter only sucessful runs (or errored-out runs respectively)
--         display = {
--           "Classic", --# display results in the command-line  area
--           "VirtualTextOk", --# display ok results as virtual text (multiline is shortened)
--
--           -- "VirtualText",             --# display results as virtual text
--           -- "VirtualLine",             --# display results as virtual lines
--           -- "TempFloatingWindow",      --# display results in a floating window
--           -- "LongTempFloatingWindow",  --# same as above, but only long results. To use with VirtualText[Ok/Err]
--           -- "Terminal",                --# display results in a vertical split
--           -- "TerminalWithCode",        --# display results and code history in a vertical split
--           -- "NvimNotify",              --# display with the nvim-notify plugin
--           -- "Api"                      --# return output to a programming interface
--         },
--
--         live_display = { "VirtualTextOk" }, --# display mode used in live_mode
--
--         -- display_options = {
--         --   terminal_scrollback = vim.o.scrollback, --# change terminal display scrollback lines
--         --   terminal_line_number = true,   --# whether show line number in terminal window
--         --   terminal_signcolumn = true,    --# whether show signcolumn in terminal window
--         --   terminal_position = "vertical", --# or "horizontal", to open as horizontal split instead of vertical split
--         --   terminal_width = 45,          --# change the terminal display option width (if vertical)
--         --   terminal_height = 20,         --# change the terminal display option height (if horizontal)
--         --   notification_timeout = 5      --# timeout for nvim_notify output
--         -- },
--
--         --# You can use the same keys to customize whether a sniprun producing
--         --# no output should display nothing or '(no output)'
--         show_no_output = {
--           "Classic",
--           "TempFloatingWindow", --# implies LongTempFloatingWindow, which has no effect on its own
--         },
--
--         --# customize highlight groups (setting this overrides colorscheme)
--         --# any parameters of nvim_set_hl() can be passed as-is
--         snipruncolors = {
--           SniprunVirtualTextOk = { bg = "#66eeff", fg = "#000000", ctermbg = "Cyan", ctermfg = "Black" },
--           SniprunFloatingWinOk = { fg = "#66eeff", ctermfg = "Cyan" },
--           SniprunVirtualTextErr = {
--             bg = "#881515",
--             fg = "#000000",
--             ctermbg = "DarkRed",
--             ctermfg = "Black",
--           },
--           SniprunFloatingWinErr = { fg = "#881515", ctermfg = "DarkRed", bold = true },
--         },
--
--         live_mode_toggle = "off", --# live mode toggle, see Usage - Running for more info
--
--         --# miscellaneous compatibility/adjustement settings
--         ansi_escape = true, --# Remove ANSI escapes (usually color) from outputs
--         inline_messages = false, --# boolean toggle for a one-line way to display output
--         --# to workaround sniprun not being able to display anything
--
--         borders = "single", --# display borders around floating windows
--         --# possible values are 'none', 'single', 'double', or 'shadow'
--       })
--     end,
--   },
--   {
--     "chipsenkbeil/org-roam.nvim",
--     version = "*",
--     event = "VeryLazy",
--     ft = { "org" },
--     -- tag = "0.1.1",
--     dependencies = {
--       {
--         "nvim-orgmode/orgmode",
--         -- tag = "0.3.7",
--       },
--     },
--     config = function()
--       require("org-roam").setup({
--         directory = "~/org_roam_files",
--         -- optional
--         org_files = {
--           "~/another_org_dir",
--           "~/some/folder/*.org",
--           "~/a/single/org_file.org",
--         },
--       })
--     end,
--   },
--   {
--     "nvim-orgmode/orgmode",
--     version = "*",
--     event = "VeryLazy",
--     ft = { "org" },
--     config = function()
--       -- Setup orgmode
--       require("orgmode").setup({
--         org_agenda_files = "~/org/**/*",
--         org_default_notes_file = "~/org/refile.org",
--         org_startup_folder = "showeverything",
--         org_todo_keywords = { "TODO(t)", "WAITING(w)", "NEXT(n)", "|", "DONE(d)", "DELEGATED(D)" },
--         org_hide_emphasis_markers = true,
--         calendar_week_start_day = 0, -- 0 = Sunday, 1 = Monday
--       })
--
--       require("org-bullets").setup({
--         concealcursor = false, -- If false then when the cursor is on a line underlying characters are visible
--         symbols = {
--           -- list symbol
--           list = "•",
--           -- headlines can be a list
--           headlines = { "◉", "○", "✸", "✿", "", "", "", "" },
--           checkboxes = {
--             half = { "", "@org.checkbox.halfchecked" },
--             done = { "✓", "@org.keyword.done" },
--             todo = { "˟", "@org.keyword.todo" },
--           },
--         },
--       })
--
--       local menu = require("org-modern.menu")
--
--       require("orgmode").setup({
--         ui = {
--           menu = {
--             handler = function(data)
--               menu:new():open(data)
--             end,
--           },
--         },
--       })
--
--       require("render-markdown").setup({
--         completions = {
--           lsp = {
--             enabled = true,
--           },
--           blink = {
--             enabled = true,
--           },
--         },
--       })
--
--       -- NOTE: If you are using nvim-treesitter with ~ensure_installed = "all"~ option
--       -- add ~org~ to ignore_install
--       -- require('nvim-treesitter.configs').setup({
--       --   ensure_installed = 'all',
--       --   ignore_install = { 'org' },
--       -- })
--     end,
--   },
-- }
