local hipatterns = require("mini.hipatterns")

local censor_extmark_opts = function(_, match, _)
  local mask = string.rep("*", vim.fn.strchars(match))
  return {
    virt_text = { { mask, "Comment" } },
    virt_text_pos = "overlay",
    priority = 200,
    right_gravity = false,
  }
end

local words = require("config.colors").words

-- Catppuccin Mocha Colors
-- local words = {
--   -- red = "#ff0000",
--   -- green = "#00ff00",
--   -- blue = "#0000ff",
--   -- black = "#000000",
--   -- white = "#ffffff",
--
--   black = "#11111b",
--   magenta = "#f5c2e7",
--   cyan = "#94e2d5",
--   white = "#cdd6f4",
--   rosewater = "#f5e0dc",
--   flamingo = "#f2cdcd",
--   pink = "#f5c2e7",
--   mauve = "#cba6f7",
--   red = "#f38ba8",
--   maroon = "#eba0ac",
--   peach = "#fab387",
--   yellow = "#f9e2af",
--   green = "#a6e3a1",
--   teal = "#94e2d5",
--   sky = "#89dceb",
--   sapphire = "#74c7ec",
--   blue = "#89b4fa",
--   lavender = "#b4befe",
--   text = "#cdd6f4",
--   subtext1 = "#bac2de",
--   subtext0 = "#a6adc8",
--   overlay2 = "#9399b2",
--   overlay1 = "#7f849c",
--   overlay0 = "#6c7086",
--   surface2 = "#585b70",
--   surface1 = "#45475a",
--   surface0 = "#313244",
--   base = "#1e1e2e",
--   mantle = "#181825",
--   crust = "#11111b",
-- }

local word_color_group = function(_, match)
  local hex = words[match]
  if hex == nil then
    return nil
  end
  return hipatterns.compute_hex_color_group(hex, "bg")
end

return {
  highlighters = {
    -- Highlight standalone 'FIXME', 'HACK', 'TODO', 'NOTE', 'WARN', 'PERF', 'TEST', 'FIXME'
    todo = { pattern = "%f[%w]()TODO()%f[%W]", group = "MiniHipatternsTodo" },
    hack = { pattern = "%f[%w]()HACK()%f[%W]", group = "MiniHipatternsHack" },
    warn = { pattern = "%f[%w]()WARN()%f[%W]", group = "MiniHipatternsWarn" },
    perf = { pattern = "%f[%w]()PERF()%f[%W]", group = "MiniHipatternsPerf" },
    note = { pattern = "%f[%w]()NOTE()%f[%W]", group = "MiniHipatternsNote" },
    test = { pattern = "%f[%w]()TEST()%f[%W]", group = "MiniHipatternsTest" },
    fixme = { pattern = "%f[%w]()FIXME()%f[%W]", group = "MiniHipatternsFixme" },

    -- Highlight hex color strings (`#rrggbb`) using that color
    hex_color = hipatterns.gen_highlighter.hex_color(),

    -- Highlight word color strings (`red`, `green`, `blue`, etc) using that color (Themed)
    word_color = { pattern = "%S+", group = word_color_group },

    -- Censors patterns
    censor = {
      pattern = {
        "pass: ()%S+()",
        "Pass: ()%S+()",
        "PASS: ()%S+()",
        "pass= ()%S+()",
        "Pass= ()%S+()",
        "PASS= ()%S+()",
        "pass = ()%S+()",
        "Pass = ()%S+()",
        "PASS = ()%S+()",
        "password: ()%S+()",
        "Password: ()%S+()",
        "passWord: ()%S+()",
        "PassWord: ()%S+()",
        "PASSWORD: ()%S+()",
        "password= ()%S+()",
        "Password= ()%S+()",
        "passWord= ()%S+()",
        "PassWord= ()%S+()",
        "PASSWORD= ()%S+()",
        "password = ()%S+()",
        "Password = ()%S+()",
        "passWord = ()%S+()",
        "PassWord = ()%S+()",
        "PASSWORD = ()%S+()",
        "pass word: ()%S+()",
        "Pass word: ()%S+()",
        "pass Word: ()%S+()",
        "Pass Word: ()%S+()",
        "PASS WORD: ()%S+()",
        "pass word= ()%S+()",
        "Pass word= ()%S+()",
        "pass Word= ()%S+()",
        "Pass Word= ()%S+()",
        "PASS WORD= ()%S+()",
        "pass word = ()%S+()",
        "Pass word = ()%S+()",
        "pass Word = ()%S+()",
        "Pass Word = ()%S+()",
        "PASS WORD = ()%S+()",
        "passkey: ()%S+()",
        "passKey: ()%S+()",
        "Passkey: ()%S+()",
        "PassKey: ()%S+()",
        "PASSKEY: ()%S+()",
        "passkey= ()%S+()",
        "Passkey= ()%S+()",
        "passKey= ()%S+()",
        "PassKey= ()%S+()",
        "PASSKEY= ()%S+()",
        "passkey = ()%S+()",
        "Passkey = ()%S+()",
        "passKey = ()%S+()",
        "PassKey = ()%S+()",
        "PASSKEY = ()%S+()",
        "pass key: ()%S+()",
        "Pass key: ()%S+()",
        "pass Key: ()%S+()",
        "Pass Key: ()%S+()",
        "PASS KEY: ()%S+()",
        "pass key= ()%S+()",
        "Pass key= ()%S+()",
        "pass Key= ()%S+()",
        "Pass Key= ()%S+()",
        "PASS KEY= ()%S+()",
        "pass key = ()%S+()",
        "Pass key = ()%S+()",
        "pass Key = ()%S+()",
        "Pass Key = ()%S+()",
        "PASS KEY = ()%S+()",
        "passphrase: ()%S+()",
        "Passphrase: ()%S+()",
        "passPhrase: ()%S+()",
        "PassPhrase: ()%S+()",
        "PASSPHRASE: ()%S+()",
        "passphrase= ()%S+()",
        "Passphrase= ()%S+()",
        "passPhrase= ()%S+()",
        "PassPhrase= ()%S+()",
        "PASSPHRASE= ()%S+()",
        "passphrase = ()%S+()",
        "Passphrase = ()%S+()",
        "passPhrase = ()%S+()",
        "PassPhrase = ()%S+()",
        "PASSPHRASE = ()%S+()",
        "pass phrase: ()%S+()",
        "Pass phrase: ()%S+()",
        "pass Phrase: ()%S+()",
        "Pass Phrase: ()%S+()",
        "PASS PHRASE: ()%S+()",
        "pass phrase= ()%S+()",
        "Pass phrase= ()%S+()",
        "pass Phrase= ()%S+()",
        "Pass Phrase= ()%S+()",
        "PASS PHRASE= ()%S+()",
        "pass phrase = ()%S+()",
        "Pass phrase = ()%S+()",
        "pass Phrase = ()%S+()",
        "Pass Phrase = ()%S+()",
        "PASS PHRASE = ()%S+()",
        "secretphrase: ()%S+()",
        "Secretphrase: ()%S+()",
        "secretPhrase: ()%S+()",
        "SecretPhrase: ()%S+()",
        "SECRETPHRASE: ()%S+()",
        "secretphrase= ()%S+()",
        "Secretphrase= ()%S+()",
        "secretPhrase= ()%S+()",
        "SecretPhrase= ()%S+()",
        "SECRETPHRASE= ()%S+()",
        "secretphrase = ()%S+()",
        "Secretphrase = ()%S+()",
        "secretPhrase = ()%S+()",
        "SecretPhrase = ()%S+()",
        "SECRETPHRASE = ()%S+()",
        "secret phrase: ()%S+()",
        "Secret phrase: ()%S+()",
        "secret Phrase: ()%S+()",
        "Secret Phrase: ()%S+()",
        "SECRET PHRASE: ()%S+()",
        "secret phrase= ()%S+()",
        "Secret phrase= ()%S+()",
        "secret Phrase= ()%S+()",
        "Secret Phrase= ()%S+()",
        "SECRET PHRASE= ()%S+()",
        "secret phrase = ()%S+()",
        "Secret phrase = ()%S+()",
        "secret Phrase = ()%S+()",
        "Secret Phrase = ()%S+()",
        "SECRET PHRASE = ()%S+()",
        "secretkey: ()%S+()",
        "Secretkey: ()%S+()",
        "secretKey: ()%S+()",
        "SecretKey: ()%S+()",
        "SECRETKEY: ()%S+()",
        "secretkey= ()%S+()",
        "Secretkey= ()%S+()",
        "secretKey= ()%S+()",
        "SecretKey= ()%S+()",
        "SECRETKEY= ()%S+()",
        "secretkey = ()%S+()",
        "Secretkey = ()%S+()",
        "secretKey = ()%S+()",
        "SecretKey = ()%S+()",
        "SECRETKEY = ()%S+()",
        "secret key: ()%S+()",
        "Secret key: ()%S+()",
        "secret Key: ()%S+()",
        "Secret Key: ()%S+()",
        "SECRET KEY: ()%S+()",
        "secret key= ()%S+()",
        "Secret key= ()%S+()",
        "secret Key= ()%S+()",
        "Secret Key= ()%S+()",
        "SECRET KEY= ()%S+()",
        "secret key = ()%S+()",
        "Secret key = ()%S+()",
        "secret Key = ()%S+()",
        "Secret Key = ()%S+()",
        "SECRET KEY = ()%S+()",
        "secretword: ()%S+()",
        "Secretword: ()%S+()",
        "secretWord: ()%S+()",
        "SecretWord: ()%S+()",
        "SECRETWORD: ()%S+()",
        "secretword= ()%S+()",
        "Secretword= ()%S+()",
        "secretWord= ()%S+()",
        "SecretWord= ()%S+()",
        "SECRETWORD= ()%S+()",
        "secretword = ()%S+()",
        "Secretword = ()%S+()",
        "secretWord = ()%S+()",
        "SecretWord = ()%S+()",
        "SECRETWORD = ()%S+()",
        "secret word: ()%S+()",
        "Secret word: ()%S+()",
        "secret Word: ()%S+()",
        "Secret Word: ()%S+()",
        "SECRET WORD: ()%S+()",
        "secret word= ()%S+()",
        "Secret word= ()%S+()",
        "secret Word= ()%S+()",
        "Secret Word= ()%S+()",
        "SECRET WORD= ()%S+()",
        "secret word = ()%S+()",
        "Secret word = ()%S+()",
        "secret Word = ()%S+()",
        "Secret Word = ()%S+()",
        "SECRET WORD = ()%S+()",
        "key = ()%S+()",
        "Key = ()%S+()",
        "KEY = ()%S+()",
        "productkey: ()%S+()",
        "Productkey: ()%S+()",
        "productKey: ()%S+()",
        "ProductKey: ()%S+()",
        "PRODUCTKEY: ()%S+()",
        "productkey= ()%S+()",
        "Productkey= ()%S+()",
        "productKey= ()%S+()",
        "ProductKey= ()%S+()",
        "PRODUCTKEY= ()%S+()",
        "productkey = ()%S+()",
        "Productkey = ()%S+()",
        "productKey = ()%S+()",
        "ProductKey = ()%S+()",
        "PRODUCTKEY = ()%S+()",
        "product key: ()%S+()",
        "Product key: ()%S+()",
        "product Key: ()%S+()",
        "Product Key: ()%S+()",
        "PRODUCT KEY: ()%S+()",
        "product key= ()%S+()",
        "Product key= ()%S+()",
        "product Key= ()%S+()",
        "Product Key= ()%S+()",
        "PRODUCT KEY= ()%S+()",
        "product key = ()%S+()",
        "Product key = ()%S+()",
        "product Key = ()%S+()",
        "Product Key = ()%S+()",
        "PRODUCT KEY = ()%S+()",
        "cdkey: ()%S+()",
        "CDkey: ()%S+()",
        "cdKey: ()%S+()",
        "CDKey: ()%S+()",
        "CDKEY: ()%S+()",
        "cdkey= ()%S+()",
        "CDkey= ()%S+()",
        "cdKey= ()%S+()",
        "CDKey= ()%S+()",
        "CDKEY= ()%S+()",
        "cdkey = ()%S+()",
        "CDkey = ()%S+()",
        "cdKey = ()%S+()",
        "CDKey = ()%S+()",
        "CDKEY = ()%S+()",
        "cd key: ()%S+()",
        "CD key: ()%S+()",
        "cd Key: ()%S+()",
        "CD Key: ()%S+()",
        "CD KEY: ()%S+()",
        "cd key= ()%S+()",
        "CD key= ()%S+()",
        "cd Key= ()%S+()",
        "CD Key= ()%S+()",
        "CD KEY= ()%S+()",
        "cd key = ()%S+()",
        "CD key = ()%S+()",
        "cd Key = ()%S+()",
        "CD Key = ()%S+()",
        "CD KEY = ()%S+()",
        "signkey: ()%S+()",
        "Signkey: ()%S+()",
        "signKey: ()%S+()",
        "SignKey: ()%S+()",
        "SIGNKEY: ()%S+()",
        "signkey= ()%S+()",
        "Signkey= ()%S+()",
        "signKey= ()%S+()",
        "SignKey= ()%S+()",
        "SIGNKEY= ()%S+()",
        "signkey = ()%S+()",
        "Signkey = ()%S+()",
        "signKey = ()%S+()",
        "SignKey = ()%S+()",
        "SIGNKEY = ()%S+()",
        "sign key: ()%S+()",
        "Sign key: ()%S+()",
        "sign Key: ()%S+()",
        "Sign Key: ()%S+()",
        "SIGN KEY: ()%S+()",
        "sign key= ()%S+()",
        "Sign key= ()%S+()",
        "sign Key= ()%S+()",
        "Sign Key= ()%S+()",
        "SIGN KEY= ()%S+()",
        "sign key = ()%S+()",
        "Sign key = ()%S+()",
        "sign Key = ()%S+()",
        "Sign Key = ()%S+()",
        "SIGN KEY = ()%S+()",
        "signingkey: ()%S+()",
        "Signingkey: ()%S+()",
        "signingKey: ()%S+()",
        "SigningKey: ()%S+()",
        "SIGNINGKEY: ()%S+()",
        "signingkey= ()%S+()",
        "Signingkey= ()%S+()",
        "signingKey= ()%S+()",
        "SigningKey= ()%S+()",
        "SIGNINGKEY= ()%S+()",
        "signingkey = ()%S+()",
        "Signingkey = ()%S+()",
        "signingKey = ()%S+()",
        "SigningKey = ()%S+()",
        "SIGNINGKEY = ()%S+()",
        "signing key: ()%S+()",
        "Signing key: ()%S+()",
        "signing Key: ()%S+()",
        "Signing Key: ()%S+()",
        "SIGNING KEY: ()%S+()",
        "signing key= ()%S+()",
        "Signing key= ()%S+()",
        "signing Key= ()%S+()",
        "Signing Key= ()%S+()",
        "SIGNING KEY= ()%S+()",
        "signing key = ()%S+()",
        "Signing key = ()%S+()",
        "signing Key = ()%S+()",
        "Signing Key = ()%S+()",
        "SIGNING KEY = ()%S+()",
        "encryptionkey: ()%S+()",
        "Encryptionkey: ()%S+()",
        "encryptionKey: ()%S+()",
        "EncryptionKey: ()%S+()",
        "ENCRYPTIONKEY: ()%S+()",
        "encryptionkey= ()%S+()",
        "Encryptionkey= ()%S+()",
        "encryptionKey= ()%S+()",
        "EncryptionKey= ()%S+()",
        "ENCRYPTIONKEY= ()%S+()",
        "encryptionkey = ()%S+()",
        "Encryptionkey = ()%S+()",
        "encryptionKey = ()%S+()",
        "EncryptionKey = ()%S+()",
        "ENCRYPTIONKEY = ()%S+()",
        "encryption key: ()%S+()",
        "Encryption key: ()%S+()",
        "encryption Key: ()%S+()",
        "Encryption Key: ()%S+()",
        "ENCRYPTION KEY: ()%S+()",
        "encryption key= ()%S+()",
        "Encryption key= ()%S+()",
        "encryption Key= ()%S+()",
        "Encryption Key= ()%S+()",
        "ENCRYPTION KEY= ()%S+()",
        "encryption key = ()%S+()",
        "Encryption key = ()%S+()",
        "encryption Key = ()%S+()",
        "Encryption Key = ()%S+()",
        "ENCRYPTION KEY = ()%S+()",
        "decryptionkey: ()%S+()",
        "Decryptionkey: ()%S+()",
        "decryptionKey: ()%S+()",
        "DecryptionKey: ()%S+()",
        "DECRYPTIONKEY: ()%S+()",
        "decryptionkey= ()%S+()",
        "Decryptionkey= ()%S+()",
        "decryptionKey= ()%S+()",
        "DecryptionKey= ()%S+()",
        "DECRYPTIONKEY= ()%S+()",
        "decryptionkey = ()%S+()",
        "Decryptionkey = ()%S+()",
        "decryptionKey = ()%S+()",
        "DecryptionKey = ()%S+()",
        "DECRYPTIONKEY = ()%S+()",
        "decryption key: ()%S+()",
        "Decryption key: ()%S+()",
        "decryption Key: ()%S+()",
        "Decryption Key: ()%S+()",
        "DECRYPTION KEY: ()%S+()",
        "decryption key= ()%S+()",
        "Decryption key= ()%S+()",
        "decryption Key= ()%S+()",
        "Decryption Key= ()%S+()",
        "DECRYPTION KEY= ()%S+()",
        "decryption key = ()%S+()",
        "Decryption key = ()%S+()",
        "decryption Key = ()%S+()",
        "Decryption Key = ()%S+()",
        "DECRYPTION KEY = ()%S+()",
        "gpgkey: ()%S+()",
        "GPGkey: ()%S+()",
        "gpgKey: ()%S+()",
        "GPGKey: ()%S+()",
        "GPGKEY: ()%S+()",
        "gpgkey= ()%S+()",
        "GPGkey= ()%S+()",
        "gpgKey= ()%S+()",
        "GPGKey= ()%S+()",
        "GPGKEY= ()%S+()",
        "gpgkey = ()%S+()",
        "GPGkey = ()%S+()",
        "gpgKey = ()%S+()",
        "GPGKey = ()%S+()",
        "GPGKEY = ()%S+()",
        "gpg key: ()%S+()",
        "GPG key: ()%S+()",
        "gpg Key: ()%S+()",
        "GPG Key: ()%S+()",
        "GPG KEY: ()%S+()",
        "gpg key= ()%S+()",
        "GPG key= ()%S+()",
        "gpg Key= ()%S+()",
        "GPG Key= ()%S+()",
        "GPG KEY= ()%S+()",
        "gpg key = ()%S+()",
        "GPG key = ()%S+()",
        "gpg Key = ()%S+()",
        "GPG Key = ()%S+()",
        "GPG KEY = ()%S+()",
        "sshkey: ()%S+()",
        "SSHkey: ()%S+()",
        "sshKey: ()%S+()",
        "SSHKey: ()%S+()",
        "SSHKEY: ()%S+()",
        "sshkey= ()%S+()",
        "SSHkey= ()%S+()",
        "sshKey= ()%S+()",
        "SSHKey= ()%S+()",
        "SSHKEY= ()%S+()",
        "sshkey = ()%S+()",
        "SSHkey = ()%S+()",
        "sshKey = ()%S+()",
        "SSHKey = ()%S+()",
        "SSHKEY = ()%S+()",
        "ssh key: ()%S+()",
        "SSH key: ()%S+()",
        "ssh Key: ()%S+()",
        "SSH Key: ()%S+()",
        "SSH KEY: ()%S+()",
        "ssh key= ()%S+()",
        "SSH key= ()%S+()",
        "ssh Key= ()%S+()",
        "SSH Key= ()%S+()",
        "SSH KEY= ()%S+()",
        "ssh key = ()%S+()",
        "SSH key = ()%S+()",
        "ssh Key = ()%S+()",
        "SSH Key = ()%S+()",
        "SSH KEY = ()%S+()",
      },
      group = "",
      extmark_opts = censor_extmark_opts,
    },
  },
}
